# Generated by Django 5.1.2 on 2024-11-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpamLookupify', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spamreport',
            name='last_reported_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
