# Generated by Django 5.1.2 on 2024-11-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpamLookupify', '0004_requestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='request_path',
            field=models.CharField(default='/unknown', max_length=255),
        ),
    ]
