# Generated by Django 5.1.2 on 2024-11-01 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpamLookupify', '0005_requestlog_request_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='spamreport',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spam_reports', to='SpamLookupify.contact'),
        ),
    ]
