# Generated by Django 5.1.2 on 2024-11-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpamLookupify', '0006_spamreport_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spamreport',
            name='contact',
        ),
    ]
