# Generated by Django 5.1.2 on 2024-11-01 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpamLookupify', '0008_contact_is_anonymous'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpammedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('report_count', models.IntegerField(default=1)),
                ('first_reported_at', models.DateTimeField(auto_now_add=True)),
                ('last_reported_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'phone_number')},
            },
        ),
    ]
