# Generated by Django 5.1.2 on 2024-11-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpamLookupify', '0010_spamreporters_delete_spammedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamreporters',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
